### ISSUE TITLE
Write results on an output file

### ISSUE THREAD

**Issue by tvp1** [walbermr/ga-series-forecasting#22]
We're using the console interface to print the results right now. We have to change it to writing the results on an output file.

**Comment by jlocx** [comment]
Done! From commit [e09e79d](https://github.com/walbermr/ga-series-forecasting/commit/e09e79d423f8495c3e0aa1f02eb3c01f9c2481fc) to commit [d0bff85](https://github.com/walbermr/ga-series-forecasting/commit/d0bff8596a493f73f22655d53b4123656f2d5932)
