### ISSUE TITLE
Add usage of a training and test datasets

### ISSUE THREAD

**Issue by tvp1** [walbermr/ga-series-forecasting#26]
Change the code to use the different datasets for training and testing

**Comment by jlocx** [comment]
Added support for inputing different dataset files. This issue still needs some consistency tests after dataset splitting (training and test sets), specially in **outpututils/output.py** file.

Reference commit: [0b81852](https://github.com/walbermr/ga-series-forecasting/commit/0b81852af7b950d0bf7f996c6566e42e10cab373)

**Comment by walbermr** [comment]
The tests are working fine.

Solved at: 0b81852af7b950d0bf7f996c6566e42e10cab373
